name: Run Tests and Publish Allure Report

on:
  push:
    branches:
      - main  # Запускать на коммитах в main ветку
  pull_request:
    branches:
      - main  # Запускать на pull request'ах к main ветке

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install  # Устанавливает браузеры для Playwright

      - name: Run Playwright tests with pytest and generate Allure results
        run: |
          pytest -m regression --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        if: success()  # Публиковать только если тесты прошли успешно
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages  # Ветка для GitHub Pages
